apiVersion: apps/v1
kind: Deployment
metadata:
 name: selenium-hub
 labels:
   app: selenium-hub
spec:
 replicas: 1
 selector:
   matchLabels:
     app: selenium-hub
 template:
   metadata:
     labels:
       app: selenium-hub
   spec:
     containers:
     - name: selenium-hub
       image: selenium/hub:4.0
       imagePullPolicy: IfNotPresent
       ports:
         - containerPort: 4444
         - containerPort: 4442
         - containerPort: 4443
#       resources:
#         limits:
#           memory: "1000Mi"
#           cpu: ".5"
       livenessProbe:
         httpGet:
           path: /wd/hub/status
           port: 4444
         initialDelaySeconds: 30
         timeoutSeconds: 5
       readinessProbe:
         httpGet:
           path: /wd/hub/status
           port: 4444
         initialDelaySeconds: 30
         timeoutSeconds: 5
#       env:
#         - name: SE_JAVA_OPTS
#           value: "--log-level FINEST"

---

apiVersion: v1
kind: Service
metadata:
 name: selenium-hub
 labels:
   app: selenium-hub
spec:
 ports:
 - port: 4444
   targetPort: 4444
   nodePort: 30007
   name: port0
 - port: 4442
   targetPort: 4442
   name: port1
 - port: 4443
   targetPort: 4443
   name: port2
 selector:
   app: selenium-hub
 type: NodePort
 sessionAffinity: None